### ISSUE TITLE
CAD model with documentation for HW integration

### ISSUE THREAD

**Issue by xtin** [Festo-se/festo-bionicsofthand-main#1]
It would be great to have access to a CAD model for the integration with existing arms.

**Comment by Cobothub** [comment]
Welcome Rafael! Please find the CAD Models of the BionicSoftHand 2.0 in the folder [meshes](https://github.com/Festo-se/phand-ros/tree/master/festo_phand_description/meshes). @Schwimo Could you please confirm? Thanks

**Comment by MrDio** [comment]
Welcome Rafael! Please find the CAD Models of the BionicSoftHand 2.0 in the folder [meshes](https://github.com/Festo-se/phand-ros/tree/master/festo_phand_description/meshes). @Schwimo Could you please confirm? Thanks

**Comment by Schwimo** [comment]
The hardware is currently not open source.
